hash-format = "sha256"

[[files]]
file = "_config.yml"

[[files]]
file = "mods/Essential-fabric_1-18-2.jar"

[[files]]
file = "mods/appleskin.toml"
metafile = true

[[files]]
file = "mods/balm-fabric-3.0.0+0.jar"

[[files]]
file = "mods/cloth-config.toml"
metafile = true

[[files]]
file = "mods/defaultoptions-fabric-1.18.1-14.1.0.jar"

[[files]]
file = "mods/krypton.toml"
metafile = true

[[files]]
file = "mods/lithium.toml"
metafile = true

[[files]]
file = "mods/qsl.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.toml"
metafile = true

[[files]]
file = "mods/sodium.toml"
metafile = true

[[files]]
file = "mods/starlight.toml"
metafile = true
