name = "Chronos Client"
author = "ubionexd"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0478c540799af3f004fecdbc3db4a5d987178bfc3468078fccfa3acb9491a5df"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
