name = "Chronos Classic"
author = "ubionexd"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00efdb235f64d4fdc66eb54fcb40ee03836906876b48e87f34c904041fccd2e0"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
