name = "Chronos Classic"
author = "ubionexd"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d0989adca28366fe2121778faaf2d346f7f56d666cd5d75558aa6cb5ea45bb9"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
