name = "Essential"
filename = "Essential-fabric_1-18-2.jar"
side = "client"

[download]
url = "http://cdn.essential.gg/mods/60ecf53d6b26c76a26d49e5b/62307167d8793b3874ecb4ad/Essential-fabric_1-18-2.jar"
hash-format = "sha1"
hash = "5c383c8fd994f6963de85840f2ae75c5b6be9925"